//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookinId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
    
        public virtual scheduleflight scheduleflight { get; set; }
        public virtual passenger passenger { get; set; }
    }
}
